### ISSUE TITLE
Tolgee: Cannot read properties of undefined (reading 'scopes')

### ISSUE THREAD

**Issue by matthiasbaldi** [eweren/vscode-tolgee#3]
With the current Tolgee version 3.8.2 it is not possible to fetch the translations
I get the following messages:

In the notification popup:  
```
Tolgee: Cannot read properties of undefined (reading 'scopes')
```

In the debug console:  
```
Error loading translations
TypeError: Cannot read properties of undefined (reading 'scopes')
en
```

Do you have an idea what here happens?

**Comment by eweren** [comment]
Either way I will close this issue, since this repo is probably so outdated, that fixing this specific error wouldn't even make things work 🤫
